apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
  tags:
    - javascript
  links:
    - url: https://www.vangoghmuseum.nl/en/art-and-stories/art/vincent-van-gogh
      title: Van Gogh Digital Gallery
spec:
  type: website
  lifecycle: production
  owner: guests
  providesApis: 
    - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: guests
  apiprovidedBy: artist-web
  definition: 
    $text: https://raw.githubusercontent.com/ShrinidhiSS/backstage/master/examples/openapi/art-web-spec.yaml